CREATE DATABASE LIVRARIA;
USE LIVRARIA;

CREATE TABLE LIVROS(
LIVCODIGO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
LIVTITULO VARCHAR(40) NOT NULL,
LIVEDITORA VARCHAR(40) NOT NULL,
LIVQUANTIDADE INT NOT NULL);

CREATE TABLE EXEMPLARES(
CODIGO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
DATA_COMPRA DATE NOT NULL,
SITUACAO VARCHAR(15) NOT NULL,
VALORPAGO DOUBLE NOT NULL,
CODIGOLIVRO INT NOT NULL,
FOREIGN KEY (CODIGOLIVRO) REFERENCES LIVROS(LIVCODIGO));

CREATE TABLE USUARIO(
ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
QUANTIADE_DE_LIVROS INT NOT NULL);


CREATE TABLE EMPRESTIMO(
ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
DT_EMPRESTIMO DATE NOT NULL,
DT_DEVOLUCAO DATE NOT NULL,
ID_USUARIO INT NOT NULL,
EXECODIGO INT NOT NULL,
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
FOREIGN KEY (EXECODIGO) REFERENCES EXEMPLARES(CODIGO));

INSERT INTO
LIVROS(LIVTITULO,LIVEDITORA,LIVQUANTIDADE) VALUES ("Banco de Dados","Makron",3);
INSERT INTO
LIVROS(LIVTITULO,LIVEDITORA,LIVQUANTIDADE) VALUES ("C++","Ciência Moderna",2);
INSERT INTO
LIVROS(LIVTITULO,LIVEDITORA,LIVQUANTIDADE) VALUES ("Engenharia de Software","Makron",1);

select * from LIVROS;

INSERT INTO
EXEMPLARES(DATA_COMPRA,SITUACAO,VALORPAGO,CODIGOLIVRO) VALUES ("2003-04-30","Disponível",70,1);
INSERT INTO
EXEMPLARES(DATA_COMPRA,SITUACAO,VALORPAGO,CODIGOLIVRO) VALUES ("2003-04-30","Disponível",70,1);
INSERT INTO
EXEMPLARES(DATA_COMPRA,SITUACAO,VALORPAGO,CODIGOLIVRO) VALUES ("2003-04-30","Disponível",70,1);
INSERT INTO
EXEMPLARES(DATA_COMPRA,SITUACAO,VALORPAGO,CODIGOLIVRO) VALUES ("2002-10-15","Disponível",65,2);
INSERT INTO
EXEMPLARES(DATA_COMPRA,SITUACAO,VALORPAGO,CODIGOLIVRO) VALUES ("2002-10-15","Disponível",65,2);
INSERT INTO
EXEMPLARES(DATA_COMPRA,SITUACAO,VALORPAGO,CODIGOLIVRO) VALUES ("2003-01-20","Disponível",110,3);

select * from EMPRESTIMO;

INSERT INTO
USUARIO(NOME,QUANTIADE_DE_LIVROS) VALUES ("José da Silva",5);
INSERT INTO
USUARIO(NOME,QUANTIADE_DE_LIVROS) VALUES ("João Benedito",2);
INSERT INTO
USUARIO(NOME,QUANTIADE_DE_LIVROS) VALUES ("Simone Cristina de Nogueira ",1);

select * from USUARIO;

INSERT INTO
EMPRESTIMO(DT_EMPRESTIMO,DT_DEVOLUCAO,ID_USUARIO,EXECODIGO) VALUES ("2003-05-25","2003-06-25",3,1);
INSERT INTO
EMPRESTIMO(DT_EMPRESTIMO,DT_DEVOLUCAO,ID_USUARIO,EXECODIGO) VALUES ("2003-05-08","2003-06-08",2,3);
INSERT INTO
EMPRESTIMO(DT_EMPRESTIMO,DT_DEVOLUCAO,ID_USUARIO,EXECODIGO) VALUES ("2003-05-25","2003-06-25",2,4);
INSERT INTO
EMPRESTIMO(DT_EMPRESTIMO,DT_DEVOLUCAO,ID_USUARIO,EXECODIGO) VALUES ("2003-06-01","2003-07-01",1,2);
INSERT INTO
EMPRESTIMO(DT_EMPRESTIMO,DT_DEVOLUCAO,ID_USUARIO,EXECODIGO) VALUES ("2003-06-01","2003-07-01",1,5);
INSERT INTO
EMPRESTIMO(DT_EMPRESTIMO,DT_DEVOLUCAO,ID_USUARIO,EXECODIGO) VALUES ("2003-06-01","2003-07-01",1,6);

SELECT * FROM EMPRESTIMO;

-- Exercicio 3A
select MAX(valorpago) from exemplares;
select MIN(valorpago) from exemplares;

-- Exercicio 3B
select * from exemplares order by DATA_COMPRA;

-- Exercicio 3C
UPDATE LIVROS SET LIVTITULO = "C++ - Guia para Iniciantes" WHERE LIVCODIGO = 2;
SELECT * FROM LIVROS;

-- Exercicio 3D
UPDATE EXEMPLARES SET VALORPAGO = VALORPAGO +(VALORPAGO*0.15);
SELECT * FROM EXEMPLARES;

-- Exercicio 3E
SELECT COUNT(CODIGO) FROM EXEMPLARES;

-- Exercicio 3F
ALTER TABLE LIVROS ADD DESCRICAO VARCHAR(100);
ALTER TABLE LIVROS ADD COMENTARIO VARCHAR(100);
SELECT * FROM LIVROS;

-- Exercicio 3G
ALTER TABLE LIVROS DROP COMENTARIO;

-- FIM DA LISTA
